### ISSUE TITLE
SUSHI Tutorial: step 4, spelling mistake?

### ISSUE THREAD

**Issue by blestab** [FSHSchool/site#38]
In Step 4: Run SUSHI, there is what i believe to be  a spelling mistake where the example says "krilling it" instead of "killing it"? 
Here are some definitions of krilling from the interwebs, https://www.urbandictionary.com/define.php?term=Krilling, https://slangdefine.org/k/krilling-446e.html

**Comment by cmoesel** [comment]
Hi @blestab -- thank you for bringing this to our attention.  SUSHI has a set of random puns it will display and "krilling it" is one of the puns -- a play on words intended to refer to the small crustaceans called [krill](https://en.wikipedia.org/wiki/Krill).  The pun was a play on words with the phrase "killing it" (as you guessed).

BUT... we did not realize that there was a _slang_ meaning for _krilling_.  That was definitely a mistake, so we will remove the "krilling it" pun from SUSHI and the documentation.

Thanks again for letting us know.

**Comment by blestab** [comment]
> Hi @blestab -- thank you for bringing this to our attention. SUSHI has a set of random puns it will display and "krilling it" is one of the puns -- a play on words intended to refer to the small crustaceans called [krill](https://en.wikipedia.org/wiki/Krill). The pun was a play on words with the phrase "killing it" (as you guessed).
> 
> BUT... we did not realize that there was a _slang_ meaning for _krilling_. That was definitely a mistake, so we will remove the "krilling it" pun from SUSHI and the documentation.
> 
> Thanks again for letting us know.

I thought it was some sorta pun but I wasn't 100% sure LOL.
